parameters:
    ee.dataexporter.class: AntQa\Bundle\DataExporterBundle\Service\DataExporter

services:
    ee.dataexporter:
        class: %ee.dataexporter.class%
        public: true
        arguments:
          - %kernel.bundles%
          - @templating
          - @?knp_snappy.pdf
